- README.md
Using the suggested JSON data from the README when creating a dataset results in a validation error:
```
An error occured: Validation error
Cause:
["Additional properties are not allowed ('processing_stage' was unexpected)"]
```
It seems that `processing_stage` isn't an accepted key, so remove it from the guide.
> Remove processing stage from example dataset JSON

- origocli/io.py
Make commands reading from stdin more convenient by allowing them to read input from a tty as well, as is customary among standard UNIX text tools.
> DP-784 Allow reading stdin from a tty

- origocli/data/boilerplate/bin/run.sh
The line must be commented out for the script to run.
> Tweak message from boilerplate run script

- origocli/commands/pipelines/pipelines.py
- origocli/commands/pipelines/schemas.py
- origocli/commands/status.py
Turn f-strings without placeholders into normal strings to stop flake8 from complaining about: "F541 f-string is missing placeholders".
> Turn f-strings without placeholders into normal strings

- origocli/commands/pipelines/instances.py
- requirements.txt
- setup.py
Remove the GPL-licensed fuzzywuzzy and python-levenshtein libraries to avoid having to re-license Origo CLI.
They were only used for an experimental feature.
> DP-1091 Remove fuzzywuzzy and python-levenshtein

- .gitignore
- README.md
- doc/Makefile
- doc/conf.py
- doc/index.md
- requirements.txt
- setup.py
Use Sphinx to render the documentation, making it suitable for hosting at readthedocs.org.
A preview can be found at https://origo-cli.readthedocs.io/en/readthedocs/.
> DP-1119 Use Sphinx for documentation generation

- CHANGELOG.md
- doc/datasets.md
- origocli/commands/datasets/datasets.py
- tests/origocli/commands/datasets/datasets_test.py
Overhaul the syntax of the `origo datasets cp` command. Four different URI formats are now supported when specifying the dataset to upload to or download from:
- `ds:{dataset_id}`
- `ds:{dataset_id}/{version}`
- `ds:{dataset_id}/{version}/latest`
- `ds:{dataset_id}/{version}/{edition}`
The two first forms will automatically create new editions on upload.
Support for the `ds://` prefix and support for providing positional versions and editions has been removed.
Test failures are addressed in https://github.com/oslokommune/origo-cli/pull/63.
Resolves https://github.com/oslokommune/origo-cli/issues/18.
> DP-1219 Syntax overhaul for `origo datasets cp`

- CHANGELOG.md
- origocli/commands/datasets/datasets.py
- origocli/commands/events.py
- origocli/io.py
- tests/origocli/commands/events_test.py
- tests/origocli/io_test.py
Expand `~` to the home directory in arguments to the `--file` option, such as in `origo datasets create --file=~/Documents/my-dataset.json`.
> DP-1269 Expand `~` to home directory in `--file` args

- origocli/commands/events.py
Unbreak the `origo events put` command by removing a duplicated call to `read_json`.
> DP-1289 Unbreak the `origo events put` command

- CHANGELOG.md
- setup.py
Include all datafiles required by the boilerplate command in the package distribution.
> DP-1287 Include missing datafiles in distribution

- doc/datasets.md
Update the documentation on dataset versions now that a version "1" is created by default for new datasets.
> Update dataset version documentation

- origocli/data/boilerplate/bin/run.sh
The syntax of the `datasets cp` command was changed in e276485506efdeefe1635b4bdc0e49142a7782f1 to use dataset URIs instead of positional arguments. Update the boilerplate script accordingly.
> Port boilerplate script to the new `cp` syntax

- CHANGELOG.md
- origocli/commands/datasets/boilerplate/boilerplate.py
- origocli/commands/datasets/boilerplate/config.py
Unify the questions on dataset access rights and confidentiality in the boilerplate questionnaire. Also give the choices more explanatory labels.
> DP-1320 Don't ask twice about access rights

- CHANGELOG.md
- origocli/commands/datasets/boilerplate/boilerplate.py
- origocli/commands/datasets/boilerplate/config.py
- origocli/commands/datasets/boilerplate/validator.py
- origocli/commands/pipelines/instances.py
- origocli/data/boilerplate/bin/run.sh
- origocli/data/boilerplate/pipeline/csv-to-parquet/pipeline.json
- origocli/data/boilerplate/pipeline/data-copy/pipeline.json
- tests/origocli/commands/datasets/boilerplate/validator_test.py
Don't prompt for an AWS account ID in the boilerplate command. This is no longer needed once pipeline processors can be referenced by their ID instead of their full ARN (which includes the AWS account ID).
> DP-1320 Don't prompt for account ID in boilerplate

- origocli/data/boilerplate/pipeline/csv-to-parquet/pipeline.json
- origocli/data/boilerplate/pipeline/data-copy/pipeline.json
Simplify the pipeline configurations used by the boilerplate command by removing the obsolete fields `useLatestEdition`, `schemaId`, and `transformation`.
> DP-1362 Simplify boilerplate pipeline configs

- CHANGELOG.md
- doc/datasets.md
- origocli/commands/datasets/boilerplate/boilerplate.py
- origocli/commands/datasets/boilerplate/config.py
- origocli/commands/datasets/datasets.py
- origocli/commands/datasets/wizards.py
- origocli/data/boilerplate/dataset/dataset-version-edition.json
- tests/origocli/cli_test.py
Make `origo datasets create` run a dataset creation wizard for setting up a new dataset complete with a processing pipeline, ready to receive files.
The `--file` parameter can still be used to create a dataset from a configuration file.
> DP-1310 Add dataset creation wizard

- CHANGELOG.md
- origocli/commands/datasets/datasets.py
The `datasets download` command was removed in commit 06093e7871e440882967afc7a596b690374aa304, but remained in the `datasets download` help text. Remove it.
> Remove `datasets download` from help text

- CHANGELOG.md
- okdata/cli/commands/datasets/boilerplate/config.py
- okdata/cli/commands/datasets/wizards.py
Support creating datasets without a pipeline in the dataset creation wizard. This is useful for advanced users who want to set up their pipelines manually.
> Support creating datasets without a pipeline

- requirements.txt
- setup.py
Require version 0.5.2 or higher of `okdata-sdk`. This is necessary because of the switch from native namespace packages to the old-style `pkg_resources` method.
> Bump required `okdata-sdk` version

- CHANGELOG.md
- okdata/cli/commands/datasets/boilerplate/config.py
Offer the `excel-to-csv` pipeline as a choice in the dataset creation wizard, alongside the existing `data-copy` and `csv-to-parquet` pipelines.
Depends on deployment of:
~~https://github.oslo.kommune.no/origo-dataplatform/dataplatform-config/pull/513~~
~~https://github.oslo.kommune.no/origo-dataplatform/dataplatform-config/pull/514~~
~~https://github.oslo.kommune.no/origo-dataplatform/dataplatform-config/pull/515~~
~~https://github.oslo.kommune.no/origo-dataplatform/dataplatform-config/pull/517~~
~~https://github.oslo.kommune.no/origo-dataplatform/csv-transformer/pull/40~~
~~https://github.oslo.kommune.no/origo-dataplatform/csv-transformer/pull/41~~
> Offer ready baked Excel to CSV pipeline

- CHANGELOG.md
- okdata/cli/commands/datasets/boilerplate/boilerplate.py
- okdata/cli/commands/datasets/boilerplate/config.py
- okdata/cli/commands/datasets/boilerplate/validator.py
- okdata/cli/commands/datasets/wizards.py
- tests/origocli/commands/datasets/boilerplate/filter_test.py
- tests/origocli/commands/datasets/boilerplate/validator_test.py
Adds new metadata fields (`spatial`, `spatialResolutionInMeters`, `conformsTo`, `license`) to the dataset creation wizard. The boilerplate wizard is currently kept as is for now. Also added styling for (what the wizard considers) required choices.
> DP-1556: Add additional metadata fields to wizard (geodata)

- CHANGELOG.md
- doc/datasets.md
- okdata/cli/commands/datasets/boilerplate/boilerplate.py
- okdata/cli/commands/datasets/wizards.py
- okdata/cli/data/boilerplate/bin/run.sh
- okdata/cli/data/boilerplate/dataset/dataset.json
- okdata/cli/data/output-format/events_stream_config.json
- tests/origocli/commands/datasets/datasets_test.py
- tests/origocli/commands/events_test.py
Depends on deployment of https://github.oslo.kommune.no/origo-dataplatform/metadata-api/pull/122 and https://github.oslo.kommune.no/origo-dataplatform/event-stream-api/pull/53.
> DP-1633 Remove usage of `confidentiality`

- CHANGELOG.md
- okdata/cli/commands/events.py
- tests/origocli/commands/events_test.py
Dataset URIs are case sensitive, so don't lowercase them when parsing their parts.
> DP-1777 Don't lowercase dataset URIs

- okdata/cli/commands/datasets/boilerplate/config.py
Canonical URIs should be used for the license field (though we should still use those nicer URLs when displaying links to the license documents).
> DP-1839 Use canonical license URIs

- requirements.txt
- setup.py
Raise the required okdata-sdk version to the one that supports PyJWT>=2.
> Raise required okdata-sdk version

- CHANGELOG.md
- doc/webhooks.md
- okdata/cli/commands/datasets/datasets.py
- okdata/cli/commands/permissions.py
- okdata/cli/commands/webhook_tokens.py
- okdata/cli/data/output-format/webhook_token_list_config.json
- okdata/cli/data/output-format/webhooks_token_config.json
- requirements.txt
- setup.py
- tests/origocli/commands/webhook_tokens_test.py
Use the new permission API based `WebhookClient` from the SDK instead of the deprecated `SimpleDatasetAuthorizerClient`.
Webhook tokens are now tied to an operation on a dataset (read, write), instead of a specific service.
> DP-2079 Use the new `WebhookClient`

- okdata/cli/__main__.py
- okdata/cli/commands/pubreg/__init__.py
- okdata/cli/commands/pubreg/client.py
- okdata/cli/commands/pubreg/pubreg.py
- okdata/cli/data/output-format/pubreg_client_keys_config.json
Add an initial public register command for listing the keys of a Maskinporten client. The command is currently going rogue and staying undocumented, since it's only intended for internal use for the time being.
> DP-2288 Add rogue command `pubreg list-keys`

- okdata/cli/command.py
- okdata/cli/commands/datasets/datasets.py
- okdata/cli/commands/events.py
- okdata/cli/commands/pipelines/pipelines.py
- okdata/cli/commands/status.py
- okdata/cli/commands/webhook_tokens.py
- tests/origocli/commands/pipeline_test.py
Avoid overwriting the `sdk` attribute in sub-classes of `BaseCommand` as suggested by CodeQL. Make some additional cleanups along the way while we're at it.
> T#160 Avoid overwriting attributes in sub-classes

- okdata/cli/commands/pubreg/wizards.py
List "test" first to make it harder to select "prod" by accident.
> T#166 Switch "prod" and "test" in env menu

- okdata/cli/commands/pubreg/pubreg.py
It seems that the command usage strings need explicit `[options]` clauses in order to make options work.
> Make `pubreg` options work

- okdata/cli/commands/pubreg/pubreg.py
- okdata/cli/commands/pubreg/wizards.py
Change the generated Maskinporten client name from `<team>-<provider>-<env>-<uuid>` to `<team>-<provider>-<integration>`, which is closer to the pattern used for existing clients.
> T#169 Tweak Maskinporten client name pattern

- okdata/cli/output.py
Drop milli- and microseconds, and display timezone aware datetimes in the local timezone.
> Prettify datetimes in table listings

- okdata/cli/__main__.py
- okdata/cli/command.py
- okdata/cli/data/boilerplate/bin/run.sh
- tests/origocli/cli_test.py
- tests/origocli/commands/datasets/boilerplate/validator_test.py
Handle more general exceptions from the `requests` library, such as connection errors and retry errors.
> T#167 Handle more general request errors

- okdata/cli/commands/pubreg/client.py
- okdata/cli/commands/pubreg/pubreg.py
Deleting keys doesn't cause changes in SSM anymore. The key parameters will be cleaned out when the client itself is deleted instead.
> Key deletion doesn't affect SSM anymore

- okdata/cli/commands/pubreg/client.py
- okdata/cli/commands/pubreg/pubreg.py
- okdata/cli/commands/pubreg/wizards.py
Send team ID, provider and integration to the Maskinporten API so the client name can be constructed there, instead of making it in the CLI.
Real team IDs will later be fetched from Keycloak.
> T#180 Tweak client creation payload

- CHANGELOG.md
- doc/pubreg.md
- okdata/cli/commands/pubreg/client.py
- okdata/cli/commands/pubreg/pubreg.py
- okdata/cli/commands/pubreg/wizards.py
- okdata/cli/data/output-format/pubreg_audit_log_config.json
- okdata/cli/output.py
Add a new `pubreg audit-log` command for viewing the audit logs of Maskinporten clients.
Depends on https://github.com/oslokommune/okdata-maskinporten-api/pull/98.
> T#274 Add `pubreg audit-log` command

- CHANGELOG.md
- README.md
- doc/teams.md
- okdata/cli/__main__.py
- okdata/cli/command.py
- okdata/cli/commands/teams.py
- okdata/cli/data/output-format/teams_config.json
- okdata/cli/output.py
- requirements.txt
- setup.py
Also add the initial member of the family: `teams ls`.
Depends on https://github.com/oslokommune/okdata-sdk-python/pull/101 being released as 2.2.0 and this PR being updated (`setup.py` + `requirements.txt`) to reflect this.
> T#294 Start a new "teams" family of commands

- doc/teams.md
- okdata/cli/commands/teams/questions.py
- okdata/cli/commands/teams/teams.py
- okdata/cli/commands/teams/wizards.py
- okdata/cli/data/output-format/team_members_config.json
Add `teams list-members` command for listing the members of a team.
~~Depends on https://github.com/oslokommune/okdata-permission-api/pull/60, https://github.com/oslokommune/okdata-cli/pull/170, and https://github.com/oslokommune/okdata-sdk-python/pull/103 being released (and setup.py + requirements.txt being updated in this PR to reflect this).~~
~~Depends on https://github.com/oslokommune/okdata-cli/pull/171.~~
> T#298 Add `teams list-members` command

- CHANGELOG.md
- okdata/cli/commands/pubreg/client.py
Depends on ~~https://github.com/oslokommune/okdata-maskinporten-api/pull/124~~.
> Update action and URL for `pubreg delete-client`

- CHANGELOG.md
- okdata/cli/commands/datasets/datasets.py
- okdata/cli/commands/status.py
Add a `--watch` option to the `okdata status` to watch the status of a dataset upload.
> Add option for `okdata status` to wait

- CHANGELOG.md
- okdata/cli/commands/datasets/datasets.py
- tests/origocli/commands/datasets/datasets_test.py
Change the `datasets ls` syntax from `ls {dataset_id} {version} {edition}` to `ls {dataset_id/version/edition}`.
This has a few advantages:
* It matches the URI syntax used by the `datasets cp` command.
* It makes it easier to copy-paste version/edition IDs output by the CLI directly into the `ls` command, since the CLI always outputs on the dataset_id/version/edition format.
* It avoids the cryptic error that used to happen when attempting to use slashes in the dataset ID by mistake.
> Make `datasets ls` take a single URI argument

- CHANGELOG.md
- okdata/cli/commands/datasets/datasets.py
- okdata/cli/date.py
- requirements.txt
- setup.py
- tests/origocli/commands/datasets/datasets_test.py
Fix the timestamps used in the names of automatically created editions. Previously it was assumed that the user always operated in UTC+2.
> Fix timestamps for auto created editions

- CHANGELOG.md
- okdata/cli/commands/datasets/datasets.py
Improve error messages in the `datasets ls` and `datasets cp` commands when a given dataset doesn't exist.
Previously one would get variably misleading messages depending on the degree of dataset/version/edition given. Now it gives a consistent error message that the dataset doesn't exist when it doesn't.
> Improve error messages for non-existing datasets

- CHANGELOG.md
- doc/permissions.md
- okdata/cli/commands/permissions.py
- tests/origocli/commands/permissions_test.py
Add a shorthand for granting a user all permissions on a resource by not specifying the `scope` parameter to the `permissions add` command, similar to the way `permissions rm` works.
> Add shorthand for granting a user all permissions

- CHANGELOG.md
- okdata/cli/__main__.py
- okdata/cli/command.py
Add new commands `okdata -e` and `okdata -v` for printing the current environment and the current version of okdata-cli, respectively.
> Add `okdata -e` and `okdata -v`

- CHANGELOG.md
- okdata/cli/command.py
- okdata/cli/commands/datasets/questions.py
- okdata/cli/commands/datasets/wizards.py
- okdata/cli/commands/pubs/pubs.py
- okdata/cli/commands/teams/teams.py
- tests/origocli/commands/teams_test.py
Also warn when a dataset is about to be registered as green (public).
> Make red the default dataset visibility choice

- CHANGELOG.md
- okdata/cli/commands/datasets/datasets.py
- tests/origocli/commands/datasets/datasets_test.py
Make the dataset/version/edition URI parsing more robust by not erroring out when too many components are passed.
> Robustify dataset/version/edition URI parsing

- CHANGELOG.md
- okdata/cli/commands/datasets/datasets.py
- okdata/cli/commands/datasets/questions.py
- okdata/cli/commands/datasets/wizards.py
Add a new command `datasets create-pipeline` for creating pipelines for existing datasets.
> Add command for creating pipelines

- CHANGELOG.md
- okdata/cli/commands/datasets/questions.py
Make the dataset creation wizard able to create event type datasets.
Remove support for the obsolete database type.
> Add event type datasets to the creation wizard

- okdata/cli/commands/pubs/questions.py
It was noted by a user that the default choice for all "do you want to delete stuff?" questions is "no", except for the question about whether you want to delete keys from Parameter Store.
Change that default to be in line with the others.
> Don't delete keys from SSM by default

- CHANGELOG.md
- okdata/cli/commands/datasets/datasets.py
- okdata/cli/data/output-format/datasets_config.json
- okdata/cli/data/output-format/datasets_config_verbose.json
- okdata/cli/data/output-format/datasets_dataset_version_config.json
- okdata/cli/data/output-format/datasets_dataset_version_edition_config.json
- okdata/cli/data/output-format/datasets_dataset_version_edition_distributions_config.json
- okdata/cli/data/output-format/datasets_dataset_versions_config.json
Also add a new option `--verbose` for the `datasets ls` command which lists every relevant metadata field for the listed datasets.
> Streamline dataset listings
